

export const GetProducts = {
  GET_PRODUCTS_REQUEST: 'GET_PRODUCTS_REQUEST',
  GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',
  GET_PRODUCTS_FAILURE: 'GET_PRODUCTS_FAILURE',
}

export const PaginateProducts = {
  PAGINATE_PRODUCTS_REQUEST: 'PAGINATE_PRODUCTS_REQUEST',
  PAGINATE_PRODUCTS_SUCCESS: 'PAGINATE_PRODUCTS_SUCCESS',
  PAGINATE_PRODUCTS_FAILURE: 'PAGINATE_PRODUCTS_FAILURE',
}

export const CreateProduct = {
  CREATE_PRODUCT_REQUEST: 'CREATE_PRODUCT_REQUEST',
  CREATE_PRODUCT_SUCCESS: 'CREATE_PRODUCT_SUCCESS',
  CREATE_PRODUCT_FAILURE: 'CREATE_PRODUCT_FAILURE',
  CREATE_PRODUCT_VALIDATION_ERROR: 'CREATE_PRODUCT_VALIDATION_ERROR',
  RESET_CREATE_PRODUCT: 'RESET_CREATE_PRODUCT'
}

export const UpdateProduct = {
  UPDATE_PRODUCT_REQUEST: 'UPDATE_PRODUCT_REQUEST',
  UPDATE_PRODUCT_SUCCESS: 'UPDATE_PRODUCT_SUCCESS',
  UPDATE_PRODUCT_FAILURE: 'UPDATE_PRODUCT_FAILURE',
  UPDATE_PRODUCT_VALIDATION_ERROR: 'UPDATE_PRODUCT_VALIDATION_ERROR',
  RESET_UPDATE_PRODUCT: 'RESET_UPDATE_PRODUCT'
}

export const DeleteProduct = {
  DELETE_PRODUCT_REQUEST: 'DELETE_PRODUCT_REQUEST',
  DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
  DELETE_PRODUCT_FAILURE: 'DELETE_PRODUCT_FAILURE',
}

export const SearchProducts = {
  SEARCH_PRODUCT_REQUEST: 'SEARCH_PRODUCT_REQUEST',
  SEARCH_PRODUCT_SUCCESS: 'SEARCH_PRODUCT_SUCCESS',
  SEARCH_PRODUCT_FAILURE: 'SEARCH_PRODUCT_FAILURE',
}
